# Generated by Django 5.2 on 2025-11-22 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermedio'), ('A', 'Avanzado')], default='B', max_length=1, verbose_name='Nivel')),
                ('duracion', models.IntegerField(verbose_name='Duración (horas)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cupo_maximo', models.IntegerField(verbose_name='Cupo Máximo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('C', 'Completado')], default='A', max_length=1, verbose_name='Estado')),
                ('profesor', models.CharField(max_length=100, verbose_name='Profesor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
