# Generated by Django 5.2 on 2025-11-23 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('codigo_alumno', models.CharField(max_length=20, unique=True, verbose_name='Código de Alumno')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('E', 'Egresado'), ('R', 'Retirado')], default='A', max_length=1, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['dni'], name='alumnos_alu_dni_f3c964_idx'), models.Index(fields=['codigo_alumno'], name='alumnos_alu_codigo__db9489_idx'), models.Index(fields=['apellidos', 'nombres'], name='alumnos_alu_apellid_75be3f_idx')],
            },
        ),
    ]
